name: 'Network upgrade trigger - Parameters'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'parameters/**'

jobs:
  upgrade:
    name: 'Network upgrade trigger - Parameters'
    runs-on: ubuntu-latest
    environment: default
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Trigger Network Upgrade
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GIT_TOKEN }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: "devops",
            workflow_id: "network-upgrades-receiver.yml",
            ref: "main",
            inputs: {
              "type_of_deployment": "parameters",
              "parameters_json": '${{ inputs.parameters_json }}'
            }
          })
