name: 'Network upgrade trigger - Version'

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  upgrade:
    name: 'Network upgrade trigger - Version'
    runs-on: ubuntu-latest
    environment: default
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Confirm tag is in main branch
      id: tag_main
      run: |
        branches=$(git branch -r --contains tags/$GITHUB_REF_NAME)
        for branch in $branches; do
          if [[ $branch == "origin/main" ]]; then
            echo "CHECK=true" >> $GITHUB_OUTPUT
          fi
        done

        if [ "$onProtectedBranch" == false ]; then
          echo "CHECK=false" >> $GITHUB_OUTPUT
        fi

    - name: Trigger Network Upgrade
      uses: actions/github-script@v6
      if: ${{ steps.tag_main.outputs.CHECK }}
      with:
        github-token: ${{ secrets.GIT_TOKEN }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: "devops",
            workflow_id: "network-upgrades-receiver.yml",
            ref: "main",
            inputs: {
              "type_of_deployment": "version",
              "tag_to_deploy": context.ref
            }
          })
