name: 'Network upgrade trigger'

on:
  push:
    tags:

permissions:
  contents: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: default
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: View context attributes
      uses: actions/github-script@v6
      with:
        script: console.log(context)

    - name: Trigger Network Upgrade
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GIT_TOKEN }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: "network-upgrades",
            workflow_id: "upgrade.yml",
            ref: "main",
            inputs: {
              "tag_to_deploy": context.ref
            }
          })
